version: '3.8'
services:
  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
